### ISSUE TITLE
translation chapter 1

### ISSUE THREAD

**Issue by mmjsys** [ftg-iran/ddpabp-persian#16]

**Comment by shahriaarrr** [comment]
با سلام.لطفا تاریخ اتمام ترجمه را بصورت حدودی اعلام بفرمایید

**Comment by mmjsys** [comment]
تا دو ماه اینده

**Comment by mthri** [comment]
تاریخ اتمام رو روی ۱ مرداد تنظیم کردم
@mmjsys

**Comment by mthri** [comment]
@mmjsys 
سلام، ترجمه‌تون چه زمانی تمام میشه؟

**Comment by mthri** [comment]
به علت عدم پاسخگویی شما، زحمت این فصل رو یک نفر دیگه از دوستان میکشه
