### ISSUE TITLE
Chapter 13

### ISSUE THREAD

**Issue by r4mi4** [ftg-iran/ddpabp-persian#22]
I'll handle this chapter

**Comment by shahriaarrr** [comment]
سلام.جهت ترجمه یا آماده سازی؟
@r4mi4

**Comment by r4mi4** [comment]
ترجمه و آماده سازی

**Comment by shahriaarrr** [comment]
آماده سازیش انجام شده توسط یک فرد دیگه.

**Comment by shahriaarrr** [comment]
شما میتونید فرآیند ترجمه رو شروع کنید @r4mi4
