### ISSUE TITLE
Translation of chapter13

### ISSUE THREAD

**Issue by mokarramis** [ftg-iran/ddpabp-persian#37]
درخواست ترجمه فصل 13 را دارم و سعی میکنم تا آخر شهریور به اتمام برسه.

**Comment by mthri** [comment]
سلام
تا آخر شهریور دیر هست، میتونید زودتر تموم کنید؟

**Comment by mokarramis** [comment]
سلام، 
تا 1 شهریور مناسب هست؟ سعی میکنم تا این تاریخ به اتمام برسونم.

**Comment by mthri** [comment]
عالی
ممنون

**Comment by mokarramis** [comment]
> عالی ممنون

خواهش میکنم
