### ISSUE TITLE
فصل 10- Dealing with Legacy Cod

### ISSUE THREAD

**Issue by saelozahra** [ftg-iran/ddpabp-persian#42]
سلام 
تا آخر مرداد انجامش میدم اگه امکانش باشه

**Comment by saelozahra** [comment]
امکانش هست که یه سری موارد 
از امنیت در پایتون رو هم به متن کتاب اضافه کنم یا نه ؟

**Comment by mthri** [comment]
سلام
تمامی فصل های این کتاب رزرو شده ولی داخل کانال عضو بشید اگر کسی از ترجمه انصراف داد اونجا اطلاع رسانی میکنیم
همچین یک کتاب دیگه هم داریم ترجمه میکنیم که هنوز خیلی از قسمت هاش رزرو نشده، میتونید توی ترجمه اون کتاب مشارکت کنید
[secondary_color](https://github.com/ftg-iran/didp-persian)

**Comment by saelozahra** [comment]
آدرس کانال رو لطف میکنید ؟
