### ISSUE TITLE
درخواست تمدید مهلت ترجمه فصل ۳ 

### ISSUE THREAD

**Issue by khoramism** [ftg-iran/ddpabp-persian#48]
با سلام اگه ممکنه مهلت تمدید به من تا تاریخ ۳۰ ام شهریور بدید بسیار ممنون و متشکر خواهم بود

**Comment by mthri** [comment]
سلام،‌۳۰ ام دیر هست، تمامی دوستان تا نهایتا تا ۱ شهریور درخواست ثبت کردند.
اگر مایل هستید میتونم تا ۱ شهریور براتون تمدید کنم

**Comment by mthri** [comment]
تا ۱ شهریور تمدید کردم
لطفا اگر وقت نمیکنید تا اون تاریخ تموم کنید اطلاع بدید
