### ISSUE TITLE
عذرخواهی و درخواست تمدید

### ISSUE THREAD

**Issue by Hamed-ak** [ftg-iran/ddpabp-persian#50]
به نام خدا
ضمن عرض سلام و ادب خدمت شما؛
از تاخیر به وجود آمده بابت ارسال ترجمه ی [Appendix A Python 2 Versus Python 3] پوزش می طلبم. به دلیل به وجود آمدن موضوع های خارج از کنترل و غیرمترقبه. بنابراین خواهشمندم تا یکم شهریور ماه جهت جمع بندی، مرور و ارسال مهلت داده شود. پیشاپیش از تامل و شکیبایی شما کمال تشکر و سپاس را دارم.

**Comment by mthri** [comment]
سلام، سلامت باشید
تا یک شهریور تمدیدم کردم

**Comment by Hamed-ak** [comment]
به نام خدا
ضمن سلام و عرض ادب خدمت شما
بحمدا... تمام شد و در گیت هاب بارگذاری کردم. البته در جدول مهلت منو از ۲۱
مرداد به یک شهریور تغییر ندادین!
اگر امری بود، در خدمتم.

سلامت باشید و موفق

**Comment by mthri** [comment]
سلام مجدد
چرا تغییر دارم،‌صفحه رو رفرش کنید میبینید
به هرحال ممنون از شما
اگر ترجمه تموم شده و روی گیت‌هاب خودتون پوش کردی pull request بفرستید که به مخزن اصلی اضافه بشه
@Hamed-ak

**Comment by Hamed-ak** [comment]
سلام دوباره
لااقل تصویر پروفایل من هم در کنار سایر دوستان می انداختی !

**Comment by Hamed-ak** [comment]
سلام دوباره
وقت بخیر
ممنون میشم بررسی بشه. همین الآن ۴ تا pr دارین.
موفق باشی

**Comment by Hamed-ak** [comment]
ممنونم عزیزم، انجام شد.
