### ISSUE TITLE
 اشکال در لینک مطالعه و دانلود

### ISSUE THREAD

**Issue by chalist** [ftg-iran/ddpabp-persian#66]
خسته نباشید و دمتون گرم.
لینک کار نمی‌کنه 🙏

**Comment by mthri** [comment]
سلام، کدوم لینک

**Comment by chalist** [comment]
همچنین می‌توانید برای دانلود کتاب (نسخه اصلی) یا مطالعه‌ی آنلاین آن از [این لینک](https://github.com/ftg-iran/ddpabp-persian/raw/main/Book/Django_Design_Patterns_and_Best_Practices.pdf) اقدام کنید.

**Comment by chalist** [comment]
[همچنین می‌توانید برای دانلود کتاب (نسخه اصلی) یا مطالعه‌ی آنلاین آن از [این لینک](https://github.com/ftg-iran/ddpabp-persian/raw/main/Book/Django_Design_Patterns_and_Best_Practices.pdf) اقدام کنید.](https://github.com/ftg-iran/ddpabp-persian/blob/f202c69cc6630fdd0fc4d6127d37202a8d42d738/README.md?plain=1#L10)

**Comment by mthri** [comment]
به دلیل اینکه ممکن بود مشکل کپی‌رایت بخوریم فایل های اصلی کتاب رو حذف کردیم
لینک کتاب رو هم من حذف کردم
